-- 사용자
CREATE TABLE `USER` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARBINARY(255) NOT NULL,
    `role` VARCHAR(50) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- URL
CREATE TABLE `URL` (
   `id` INT AUTO_INCREMENT PRIMARY KEY,
   `original_url` VARCHAR(2083) NOT NULL,
   `short_url` VARCHAR(100) NOT NULL UNIQUE,
   `user_id` INT NOT NULL,
   `visit_count` INT DEFAULT 0,
   `use_yn` CHAR(1) DEFAULT 'Y',
   `del_yn` CHAR(1) DEFAULT 'N',
   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   CONSTRAINT `FK_USER_URLS` FOREIGN KEY (`user_id`) REFERENCES `USER` (`id`) ON DELETE CASCADE
);